version: '3.8'

services:
  backend:
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./django_backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=django_backend.settings
    platform: linux/amd64